/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'English (en-US)' language
 */
export type EnglishEnUSLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">

/*
 * Typeguard for codename of 'English (en-US)' language
 */
export function isEnglishEnUSLanguageCodename(value: string | undefined | null): value is EnglishEnUSLanguageCodename {
  return typeof value === "string" && value === ("default" satisfies EnglishEnUSLanguageCodename)
}
