/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'German (de-DE)' language
 */
export type GermanDeDELanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "de-DE">

/*
 * Typeguard for codename of 'German (de-DE)' language
 */
export function isGermanDeDELanguageCodename(value: string | undefined | null): value is GermanDeDELanguageCodename {
  return typeof value === "string" && value === ("de-DE" satisfies GermanDeDELanguageCodename)
}
