/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'Spanish (es-ES)' language
 */
export type SpanishEsESLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "es-ES">

/*
 * Typeguard for codename of 'Spanish (es-ES)' language
 */
export function isSpanishEsESLanguageCodename(value: string | undefined | null): value is SpanishEsESLanguageCodename {
  return typeof value === "string" && value === ("es-ES" satisfies SpanishEsESLanguageCodename)
}
