/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'Spanish (es-ES)' language
 */
export type SpanishEsESLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "es-ES">

/*
 * Typeguard for codename of 'Spanish (es-ES)' language
 */
export function isSpanishEsESLanguageCodename(value: string | undefined | null): value is SpanishEsESLanguageCodename {
  return typeof value === "string" && value === ("es-ES" satisfies SpanishEsESLanguageCodename)
}
