/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { MetadataSnippet } from "../snippets/metadata.generated.ts"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Blog Post' type
 */
export type BlogPostTypeCodename = keyof Pick<Record<TypeCodenames, null>, "blog_post">

/*
 * Typeguard for codename of 'Blog Post' type
 */
export function isBlogPostTypeCodename(value: string | undefined | null): value is BlogPostTypeCodename {
  return typeof value === "string" && value === ("blog_post" satisfies BlogPostTypeCodename)
}

/*
 * Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export type BlogPostType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: 72869e6e-2822-4e81-944a-d90b3148ce4a
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement

    /*
     * Image
     *
     * Codename: image
     * Id: 1361b589-f40e-4c4a-b219-62a0f3f5a8c0
     * Type: asset
     * Required: true
     */
    readonly image: Elements.AssetsElement

    /*
     * Body
     *
     * Codename: body
     * Id: e74bc043-0613-4554-8fb5-4d03a42c61a5
     * Type: rich_text
     * Required: true
     */
    readonly body: Elements.RichTextElement<CoreType>

    /*
     * URL slug
     *
     * Codename: url_slug
     * Id: cfdddb6d-ae75-431b-ac02-af463468d86b
     * Type: url_slug
     * Required: true
     */
    readonly url_slug: Elements.UrlSlugElement
  } & MetadataSnippet,
  BlogPostTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Blog Post
 */
export type BlogPostTypeElementCodenames =
  | "title"
  | "image"
  | "body"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url_slug"

/*
 * Type guard for Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export function isBlogPostType(item: IContentItem | undefined | null): item is BlogPostType {
  return item?.system.type === ("blog_post" satisfies BlogPostTypeCodename)
}
