/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { MetadataSnippet } from "../snippets/metadata.generated.ts"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"
import type { CallToActionType } from "../types/call-to-action.generated.ts"
import type { DisclaimerType } from "../types/disclaimer.generated.ts"
import type { VideoType } from "../types/video.generated.ts"

/*
 * Type representing codename of 'Page' type
 */
export type PageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "page">

/*
 * Typeguard for codename of 'Page' type
 */
export function isPageTypeCodename(value: string | undefined | null): value is PageTypeCodename {
  return typeof value === "string" && value === ("page" satisfies PageTypeCodename)
}

/*
 * Page
 *
 * Id: 4bdd2f8f-3acc-4744-b005-8f629948ec13
 * Codename: page
 */
export type PageType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 05721c93-8dcb-4daa-81b6-df690efaef61
     * Type: text
     * Required: true
     */
    readonly headline: Elements.TextElement

    /*
     * Subheadline
     *
     * Codename: subheadline
     * Id: 719d23e7-d174-498f-b0aa-46640791b5fb
     * Type: text
     * Required: true
     */
    readonly subheadline: Elements.TextElement

    /*
     * Hero Image
     *
     * Codename: hero_image
     * Id: 35be9ac2-8024-410e-ab79-78709a9695f1
     * Type: asset
     * Required: false
     */
    readonly hero_image: Elements.AssetsElement

    /*
     * Body
     *
     * Codename: body
     * Id: c5ac868e-97fe-419a-a256-635af1fb70aa
     * Type: rich_text
     * Required: false
     * Allowed content types: video, disclaimer, call_to_action
     */
    readonly body: Elements.RichTextElement<VideoType | DisclaimerType | CallToActionType>

    /*
     * URL
     *
     * Codename: url
     * Id: 31e8a7c4-b997-4112-adb9-c11730348a87
     * Type: url_slug
     * Required: true
     */
    readonly url: Elements.UrlSlugElement

    /*
     * Subpages
     *
     * Codename: subpages
     * Id: 17024df9-8457-45ed-ba2d-a2235a72dd06
     * Type: subpages
     * Required: false
     */
    readonly subpages: Elements.LinkedItemsElement<CoreType>
  } & MetadataSnippet,
  PageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Page
 */
export type PageTypeElementCodenames =
  | "headline"
  | "subheadline"
  | "hero_image"
  | "body"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url"
  | "subpages"

/*
 * Type guard for Page
 *
 * Id: 4bdd2f8f-3acc-4744-b005-8f629948ec13
 * Codename: page
 */
export function isPageType(item: IContentItem | undefined | null): item is PageType {
  return item?.system.type === ("page" satisfies PageTypeCodename)
}
