/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Academic Resources' workflow
 */
export type AcademicResourcesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "academic_resources">

/*
 * Typeguard for codename of 'Academic Resources' workflow
 */
export function isAcademicResourcesWorkflowCodename(
  value: string | undefined | null,
): value is AcademicResourcesWorkflowCodename {
  return typeof value === "string" && value === ("academic_resources" satisfies AcademicResourcesWorkflowCodename)
}

/*
 * Array of all workflow step codenames
 */
export const academicResourcesWorkflowStepCodenames = [
  "draft_a8b162c",
  "translation",
  "peer_review",
  "reviewed",
  "published",
  "archived",
  "scheduled",
] as const

/*
 * Type representing all workflow step codenames
 */
export type AcademicResourcesWorkflowStepCodenames = (typeof academicResourcesWorkflowStepCodenames)[number]

/*
 * Typeguard for workflow step codename
 */
export function isAcademicResourcesWorkflowStepCodename(
  value: string | undefined | null,
): value is AcademicResourcesWorkflowStepCodenames {
  return typeof value === "string" && (academicResourcesWorkflowStepCodenames as readonly string[]).includes(value)
}
