/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Biographies' workflow
 */
export type BiographiesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "biographies">

/*
 * Typeguard for codename of 'Biographies' workflow
 */
export function isBiographiesWorkflowCodename(value: string | undefined | null): value is BiographiesWorkflowCodename {
  return typeof value === "string" && value === ("biographies" satisfies BiographiesWorkflowCodename)
}

/*
 * Array of all workflow step codenames
 */
export const biographiesWorkflowStepCodenames = [
  "draft_97d445e",
  "staff_member_review",
  "reviewed_1778942",
  "published",
  "archived",
  "scheduled",
] as const

/*
 * Type representing all workflow step codenames
 */
export type BiographiesWorkflowStepCodenames = (typeof biographiesWorkflowStepCodenames)[number]

/*
 * Typeguard for workflow step codename
 */
export function isBiographiesWorkflowStepCodename(
  value: string | undefined | null,
): value is BiographiesWorkflowStepCodenames {
  return typeof value === "string" && (biographiesWorkflowStepCodenames as readonly string[]).includes(value)
}
