/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Patient Resources' workflow
 */
export type PatientResourcesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "patient_resources">

/*
 * Typeguard for codename of 'Patient Resources' workflow
 */
export function isPatientResourcesWorkflowCodename(
  value: string | undefined | null,
): value is PatientResourcesWorkflowCodename {
  return typeof value === "string" && value === ("patient_resources" satisfies PatientResourcesWorkflowCodename)
}

/*
 * Array of all workflow step codenames
 */
export const patientResourcesWorkflowStepCodenames = [
  "draft_b242d4d",
  "medical_review",
  "legal_review",
  "marketing_review",
  "published",
  "archived",
  "scheduled",
] as const

/*
 * Type representing all workflow step codenames
 */
export type PatientResourcesWorkflowStepCodenames = (typeof patientResourcesWorkflowStepCodenames)[number]

/*
 * Typeguard for workflow step codename
 */
export function isPatientResourcesWorkflowStepCodename(
  value: string | undefined | null,
): value is PatientResourcesWorkflowStepCodenames {
  return typeof value === "string" && (patientResourcesWorkflowStepCodenames as readonly string[]).includes(value)
}
