/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all collection codenames
 */
export const collectionCodenames = [
  "academic_content",
  "default",
  "operations",
  "patient_resources",
  "marketing_resources",
] as const

/*
 * Type representing all collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number]

/*
 * Typeguard for collection codename
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
  return typeof value === "string" && (collectionCodenames as readonly string[]).includes(value)
}
