/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
  "headline",
  "subheadline",
  "hero_image",
  "body_copy",
  "featured_content",
  "subpages",
  "title",
  "image",
  "body",
  "metadata__title",
  "metadata__keywords",
  "metadata__description",
  "url_slug",
  "name",
  "summary",
  "description",
  "team",
  "medical_specialties",
  "image_position",
  "button_label",
  "button_link",
  "url",
  "start_date",
  "end_date",
  "event_type",
  "event_topic",
  "first_name",
  "last_name",
  "prefix",
  "suffixes",
  "biography",
  "job_title",
  "phone",
  "email",
  "website",
  "video_link",
  "caption",
  "autoplay",
  "type",
  "publish_date",
  "introduction",
  "author",
  "article_type",
  "topics",
  "related_articles",
] as const

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number]

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
  return typeof value === "string" && (elementCodenames as readonly string[]).includes(value)
}
