/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = ["metadata"] as const

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number]

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
  return typeof value === "string" && (snippetCodenames as readonly string[]).includes(value)
}
