/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = [
  "general_healthcare_topics",
  "article_type",
  "medical_specialties",
  "event_type",
  "event_topic",
] as const

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number]

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
  return typeof value === "string" && (taxonomyCodenames as readonly string[]).includes(value)
}
