/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { ArticleType } from "../types/article.generated.ts"
import type { BlogPostType } from "../types/blog-post.generated.ts"
import type { CallToActionType } from "../types/call-to-action.generated.ts"
import type { DisclaimerType } from "../types/disclaimer.generated.ts"
import type { EventType } from "../types/event.generated.ts"
import type { LandingPageType } from "../types/landing-page.generated.ts"
import type { PageType } from "../types/page.generated.ts"
import type { PersonType } from "../types/person.generated.ts"
import type { ServiceType } from "../types/service.generated.ts"
import type { VideoType } from "../types/video.generated.ts"

/*
 * Array of all type codenames
 */
export const typeCodenames = [
  "landing_page",
  "blog_post",
  "service",
  "call_to_action",
  "page",
  "event",
  "person",
  "video",
  "disclaimer",
  "article",
] as const

/*
 * Type representing all type codenames
 */
export type TypeCodenames = (typeof typeCodenames)[number]

/*
 * Typeguard for type codename
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
  return typeof value === "string" && (typeCodenames as readonly string[]).includes(value)
}

/*
 * Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
 */
export type CoreType =
  | LandingPageType
  | BlogPostType
  | ServiceType
  | CallToActionType
  | PageType
  | EventType
  | PersonType
  | VideoType
  | DisclaimerType
  | ArticleType

/*
 * Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
 */
export type CodenameTypeMapping = {
  readonly landing_page: LandingPageType
  readonly blog_post: BlogPostType
  readonly service: ServiceType
  readonly call_to_action: CallToActionType
  readonly page: PageType
  readonly event: EventType
  readonly person: PersonType
  readonly video: VideoType
  readonly disclaimer: DisclaimerType
  readonly article: ArticleType
}

/*
 * Helper type that returns type based on the codename of type.
 */
export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping
  ? CodenameTypeMapping[TTypeCodename]
  : CoreType
