/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default", "patient_resources", "academic_resources", "biographies"] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
  return typeof value === "string" && (workflowCodenames as readonly string[]).includes(value)
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = [
  "draft",
  "copy_review",
  "published",
  "archived",
  "scheduled",
  "draft_b242d4d",
  "medical_review",
  "legal_review",
  "marketing_review",
  "draft_a8b162c",
  "translation",
  "peer_review",
  "reviewed",
  "draft_97d445e",
  "staff_member_review",
  "reviewed_1778942",
] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
  return typeof value === "string" && (workflowStepCodenames as readonly string[]).includes(value)
}
