/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts"

/*
 * Type representing codename of 'Article Type' taxonomy
 */
export type ArticleTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "article_type">

/*
 * Typeguard for codename of 'Article Type' taxonomy
 */
export function isArticleTypeTaxonomyCodename(value: string | undefined | null): value is ArticleTypeTaxonomyCodename {
  return typeof value === "string" && value === ("article_type" satisfies ArticleTypeTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const articleTypeTaxonomyTermCodenames = [
  "clinical_guidelines",
  "case_study",
  "research",
  "healthcare_policy_update",
  "institutional_announcement",
  "industry_updates",
  "patient_education",
  "professional_training",
  "educational",
] as const

/*
 * Type representing all taxonomy term codenames
 */
export type ArticleTypeTaxonomyTermCodenames = (typeof articleTypeTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isArticleTypeTaxonomyTermCodename(
  value: string | undefined | null,
): value is ArticleTypeTaxonomyTermCodenames {
  return typeof value === "string" && (articleTypeTaxonomyTermCodenames as readonly string[]).includes(value)
}
