/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Academic Content' collection
 */
export type AcademicContentCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "academic_content">

/*
 * Typeguard for codename of 'Academic Content' collection
 */
export function isAcademicContentCollectionCodename(
  value: string | undefined | null,
): value is AcademicContentCollectionCodename {
  return typeof value === "string" && value === ("academic_content" satisfies AcademicContentCollectionCodename)
}
