/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Common' collection
 */
export type CommonCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">

/*
 * Typeguard for codename of 'Common' collection
 */
export function isCommonCollectionCodename(value: string | undefined | null): value is CommonCollectionCodename {
  return typeof value === "string" && value === ("default" satisfies CommonCollectionCodename)
}
