/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Marketing Resources' collection
 */
export type MarketingResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "marketing_resources">

/*
 * Typeguard for codename of 'Marketing Resources' collection
 */
export function isMarketingResourcesCollectionCodename(
  value: string | undefined | null,
): value is MarketingResourcesCollectionCodename {
  return typeof value === "string" && value === ("marketing_resources" satisfies MarketingResourcesCollectionCodename)
}
