/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Operations' collection
 */
export type OperationsCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "operations">

/*
 * Typeguard for codename of 'Operations' collection
 */
export function isOperationsCollectionCodename(
  value: string | undefined | null,
): value is OperationsCollectionCodename {
  return typeof value === "string" && value === ("operations" satisfies OperationsCollectionCodename)
}
