/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Patient Resources' collection
 */
export type PatientResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "patient_resources">

/*
 * Typeguard for codename of 'Patient Resources' collection
 */
export function isPatientResourcesCollectionCodename(
  value: string | undefined | null,
): value is PatientResourcesCollectionCodename {
  return typeof value === "string" && value === ("patient_resources" satisfies PatientResourcesCollectionCodename)
}
