/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo
 * Environment: Production
 * Id: fd58c119-60b3-013c-7ac4-c7b4cf69bc7b
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Patient Resources' collection
 */
export type PatientResourcesCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "patient_resources">

/*
 * Typeguard for codename of 'Patient Resources' collection
 */
export function isPatientResourcesCollectionCodename(
  value: string | undefined | null,
): value is PatientResourcesCollectionCodename {
  return typeof value === "string" && value === ("patient_resources" satisfies PatientResourcesCollectionCodename)
}
