/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Master Demo - Multi Spaces
 * Environment: Production
 * Id: 63433181-640b-015e-bd79-e0a68d0bf9d6
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Wellness Summit 2026' collection
 */
export type WellnessSummit2026CollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "wellness_summit_2026">

/*
 * Typeguard for codename of 'Wellness Summit 2026' collection
 */
export function isWellnessSummit2026CollectionCodename(
  value: string | undefined | null,
): value is WellnessSummit2026CollectionCodename {
  return typeof value === "string" && value === ("wellness_summit_2026" satisfies WellnessSummit2026CollectionCodename)
}
